DROP TABLE IF EXISTS BRANDS;
CREATE TABLE BRANDS (  
BRAND_ID INT PRIMARY KEY, 
DESC_BRAND VARCHAR(30) NOT NULL
);

DROP TABLE IF EXISTS PRICES;
CREATE TABLE PRICES (  
PRICE_ID INT PRIMARY KEY,
BRAND_ID INT NOT NULL,
START_DATE datetime,
END_DATE datetime,
PRICE_LIST INT NOT NULL,
PRODUCT_ID INT NOT NULL,
PRIORITY INT NOT NULL,
PRICE decimal(6,2),
CURR VARCHAR(10),
FOREIGN KEY (BRAND_ID) REFERENCES BRANDS (BRAND_ID)
);
